# encoding: UTF-8

control 'C-2.7' do
  title 'Ensure access is limited to trusted devices'
  desc  "
    WorkSpaces access should be restricted to trusted devices with valid certificates.

    WorkSpaces is accessible from any supported device that is connected to the internet. When you enable access to trusted devices, Amazon WorkSpaces uses certificate-based authentication to determine whether a device is trusted.
  "
  desc  'rationale', "
    WorkSpaces access should be restricted to trusted devices with valid certificates.

    WorkSpaces is accessible from any supported device that is connected to the internet. When you enable access to trusted devices, Amazon WorkSpaces uses certificate-based authentication to determine whether a device is trusted.
  "
  desc  'check', "
    Perform the following steps to confirm that Allow Trusted Devices is set.

    From the Console:
	
    1. Log in to the WorkSpaces console at `https://console.aws.amazon.com/workspaces/`

    2. In the left pane, click `Directories`.

    3. Select the directory id link.

    4. Scroll to the `Access Control Options` section.
   
    5. Confirm that the correct `Allow` settings are in place.

    6. Confirm that certificates have been imported.

    7. Confirm that the correct device types have been enabled.

    If everything is not configured as above refer to the remediation below.
  "
  desc  'fix', "
    Perform the following steps to set the restriction Allow Trusted Devices

    Create the Certificates

    Note - It requires root certificates generated by an internal Certificate Authority (CA) and client certificates that chain up to a root certificate.
    ```
    Requirements
    - Certificates must be Base64-encoded certificate files in CRT, CERT, or PEM format.
    - Certificates must include a Common Name.
    - The maximum length of certificate chain supported is 4.
    - Use a strong encryption algorithm. Minimum SHA256 with RSA, SHA256 with ECDSA. Other options SHA381 with ECDSA, or SHA512 with ECDSA.
    - Make sure \"key usage: Digital signature\" is present on the public key.
    - For macOS, if the device certificate is in the system keychain, authorize the WorkSpaces client application to access those certificates.
    ```
    Deploy Client Certificates to the Trusted Devices
    ```
    - Client certificates must be installed on the trusted devices for your users.
    Utilize a third party tool to install the certificates or have the certificates installed locally by an administrator.
    - On Windows, the WorkSpaces client application searches for client certificates in both the user and root certificate stores.
    - On macOS, the WorkSpaces client application searches for client certificates in the entire keychain.
    ```
    Configure the Restriction

    From the Console:

    1. Login to the WorkSpaces console at `https://console.aws.amazon.com/workspaces/`

    2. In the left pane, click `Directories`.

    3. Select the directory id link.

    4. Scroll to the `Access Control Options` section and click `Edit`.
    ```
            - [Windows] Choose Only Allow Trusted Windows Devices to Access WorkSpaces.
            - [macOS] Choose Only Allow Trusted macOS Devices to Access WorkSpaces.
    ```
    5. Import up to two root certificates. For each root certificate, do the following:
    ```
             - Choose Import.
             - Copy the body of the certificate to the form.
             - Choose Import.
             (Optional) Specify whether other types of devices have access to WorkSpaces.
     ```
    6. Scroll down to the `Trusted devices` section. 

    7. Select the device types allowed to `Trusted devices`.

    8. To block access from all selected device types, click `Deny All`.

    9. Click `Save`.
  "
  tag severity:              'medium'
  tag severity_source:       'unassessed'
  tag nist:                  ['AC-3', 'AC-8 a']
  tag ksi:                   ['KSI-IAM-APM', 'KSI-IAM-ELP', 'KSI-IAM-JIT']
  tag nist_r4:               ['AC-3']
  tag cci:                   ['CCI-000213', 'CCI-000051']
  tag cis_number:            '2.7'
  tag cis_rid:               '2.7'
  tag cis_benchmark:         'CIS AWS End User Compute Services Benchmark v1.2.0'
  tag cis_rule_id:           'SV-0207r1_rule'
  tag cis_version:           '1.2.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag exec_validated:        false

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_service   = Array(input('applicable_services')).empty? || Array(input('applicable_services')).include?('workspaces')
  applicable           = applicable_partition && applicable_service

  impact 0.5
  impact 0.0 unless applicable

  only_if("WORKSPACES out of scope (partition=#{input('aws_partition')}, applicable_services=#{input('applicable_services')})") do
    applicable
  end

  describe 'WorkSpaces directories without an IP access control group restricting trusted devices (CIS 2.7)' do
    subject { aws_workspaces_inventory.directories_without_ip_group_restriction }
    it { should be_empty }
  end
end
